In [25]:
%matplotlib inline
import numpy as np
import pandas as pd
import scipy
import sklearn
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import BernoulliNB
pd.set_option('display.max_colwidth', -1) 

In [26]:
yelp_raw = pd.read_csv('/Users/elizabeth/Desktop/Thinkful Data Science/Datasets/sentiment labelled sentences/yelp_labelled.txt', delimiter= '\t', header=None)
yelp_raw.columns = ['review', 'sentiment']

keywords = ['not good', 'nasty', 'angry', 'never', 'disappointing', 'poor', 'not', 'disgusted', 'slow', 
            'bad' ,'underwhelming' ,'suck', 'flop', 'avoid', 'horrible', 'wasted','no']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    yelp_raw[str(key)] = yelp_raw.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )


data = yelp_raw[keywords]
target = yelp_raw['sentiment']

bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

In [27]:
yelp_raw.loc[yelp_raw['sentiment']==1].count()[0]/yelp_raw.shape[0]

0.5

In [44]:
yelp_raw.loc[yelp_raw['sentiment']==0].iloc[300:350, 0:2]

review  \
681  Your staff spends more time talking to themselves than me.                                                                               
685  Total brunch fail.                                                                                                                       
691  I probably won't be back, to be honest.                                                                                                  
695  Went for lunch - service was slow.                                                                                                       
696  We had so much to say about the place before we walked in that he expected it to be amazing, but was quickly disappointed.               
697  I was mortified.                                                                                                                         
698  Needless to say, we will never be back here again.                                                                                       
699  Anyways, The food was definitely not filling at all, and for the price you pay you should expect more.                                   
700  The chips that came out were dripping with grease, and mostly not edible.                                                                
701  I wasn't really impressed with Strip Steak.                                                                                              
705  I work in the hospitality industry in Paradise Valley and have refrained from recommending Cibo any longer.                              
707  Would not recommend to others.                                                                                                           
709  I mean really, how do you get so famous for your fish and chips when it's so terrible!?!                                                 
711  Not my thing.                                                                                                                            
713  If you are reading this please don't go there.                                                                                           
717  Tonight I had the Elk Filet special...and it sucked.                                                                                     
719  We ordered some old classics and some new dishes after going there a few times and were sorely disappointed with everything.             
727  A FLY was in my apple juice.. A FLY!!!!!!!!                                                                                              
730  The food was barely lukewarm, so it must have been sitting waiting for the server to bring it out to us.                                 
731  Ryan's Bar is definitely one Edinburgh establishment I won't be revisiting.                                                              
735  Probably never coming back, and wouldn't recommend it.                                                                                   
736  Friend's pasta -- also bad, he barely touched it.                                                                                        
741  It was way over fried.                                                                                                                   
742  I'm not sure how long we stood there but it was long enough for me to begin to feel awkwardly out of place.                              
743  When I opened the sandwich, I was impressed, but not in a good way.                                                                      
744  Will not be back!                                                                                                                        
748  I have watched their prices inflate, portions get smaller and management attitudes grow rapidly!                                         
754  Main thing I didn't enjoy is that the crowd is of older crowd, around mid 30s and up.                                       

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target, y_pred)

array([[147, 353],
       [ 20, 480]])

In [30]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))

With 20% Holdout: 0.6
Testing on Sample: 0.627


In [31]:
from sklearn.model_selection import cross_val_score
cross_val_score(bnb, data, target, cv=10)

array([0.68, 0.59, 0.65, 0.57, 0.62, 0.63, 0.64, 0.61, 0.6 , 0.63])

In [39]:
yelp_raw = pd.read_csv('/Users/elizabeth/Desktop/Thinkful Data Science/Datasets/sentiment labelled sentences/yelp_labelled.txt', delimiter= '\t', header=None)
yelp_raw.columns = ['review', 'sentiment']

#addeed 11 keywords
keywords = ['not good', 'nasty', 'angry', 'never', 'disappointing', 'poor', 'not', 'disgusted', 'slow', 
            'bad' ,'underwhelming' ,'suck', 'flop', 'avoid', 'horrible', 'wasted','no', "don't", "wasn't", 'down',
           'worst', 'lacking', 'boring', 'never', 'joke','gross', 'dirty', 'tasteless']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    yelp_raw[str(key)] = yelp_raw.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )


data = yelp_raw[keywords]
target = yelp_raw['sentiment']

bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

In [40]:
print(confusion_matrix(target, y_pred))

[[186 314]
 [ 25 475]]


In [41]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))
print(cross_val_score(bnb, data, target, cv=10))

With 20% Holdout: 0.635
Testing on Sample: 0.661
[0.71 0.65 0.7  0.62 0.64 0.63 0.67 0.62 0.63 0.68]


true negative review incresed, while true positive review decreased. Overall increased.

In [45]:
yelp_raw = pd.read_csv('/Users/elizabeth/Desktop/Thinkful Data Science/Datasets/sentiment labelled sentences/yelp_labelled.txt', delimiter= '\t', header=None)
yelp_raw.columns = ['review', 'sentiment']

#addeed 6 keywords
keywords = ['not good', 'nasty', 'angry', 'never', 'disappointing', 'poor', 'not', 'disgusted', 'slow', 
            'bad' ,'underwhelming' ,'suck', 'flop', 'avoid', 'horrible', 'wasted','no', "don't", "wasn't", 'down',
           'worst', 'lacking', 'boring', 'never', 'joke','gross', 'dirty', 'tasteless', 'terrible', 'waited', 'waiting',
            'mistake', 'sick', 'poor']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    yelp_raw[str(key)] = yelp_raw.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )


data = yelp_raw[keywords]
target = yelp_raw['sentiment']

bnb = BernoulliNB()

# Fit our model to the data.
bnb.fit(data, target)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(data)

In [46]:
print(confusion_matrix(target, y_pred))

[[200 300]
 [ 25 475]]


In [47]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(bnb.fit(data, target).score(data, target)))
print(cross_val_score(bnb, data, target, cv=10))

With 20% Holdout: 0.65
Testing on Sample: 0.675
[0.71 0.66 0.73 0.63 0.65 0.66 0.69 0.63 0.64 0.68]
